M48
; DRILL file {KiCad 7.0.1} date Wed Aug 30 15:18:27 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-30T15:18:27-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.1280
%
G90
G05
T1
X4.835Y-5.0547
X4.8437Y-4.787
T2
X5.1098Y-4.8207
X5.1098Y-4.9207
X5.1098Y-5.0207
T3
X4.7768Y-4.9201
T0
M30
